function Hd = IIRChebyT1HPF
%IIRCHEBYT1HPF Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
% Generated on: 12-Dec-2018 12:31:04

% Chebyshev Type I Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = 3906.25;  % Sampling Frequency

Fstop = 2;           % Stopband Frequency
Fpass = 5;           % Passband Frequency
Astop = 20;          % Stopband Attenuation (dB)
Apass = 0.1;         % Passband Ripple (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'cheby1', 'MatchExactly', match);

% [EOF]
