function Hd = IIRElliptic
%IIRElliptic Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the DSP System Toolbox 9.1.
% Generated on: 12-Dec-2018 10:52:48

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 15625;  % Sampling Frequency

Fpass = 150;     % Passband Frequency
Fstop = 180;     % Stopband Frequency
Apass = 1;       % Passband Ripple (dB)
Astop = 40;      % Stopband Attenuation (dB)
match = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);

% [EOF]
